---
name: 'Build SW Examples'
description: 'Compile Example Target SW'
inputs:
  examples-dir:
    description: 'Examples SW directory'
    required: true
    default: ''
  llvm-dir:
    description: 'LLVM TC install directory'
    required: false
    default: ''
  gnu-dir:
    description: 'GNU TC install directory'
    required: true
    default: ''
  gnu-name:
    description: 'GNU TC name'
    required: true
    default: ''
  toolchain:
    description: 'Used toolchain (Choices: llvm, gcc)'
    required: true
    default: 'llvm'
  build-type:
    description: 'Value for CMAKE_BUILD_TYPE'
    required: true
    default: 'Release'
  xlen:
    description: 'XLEN of target (matching march)'
    required: true
    default: '?'
  arch:
    description: 'Value for -march=?'
    required: true
    default: '?'
  abi:
    description: 'Value for -mabi=?'
    required: true
    default: '?'
  progs:
    description: 'Comma-separated list of programs'
    required: true
    default: 'hello_world'
  enable-summary:
    description: 'Enable Job Summary'
    required: true
outputs: {}

runs:
  using: "composite"
  steps:
    - name: Set CMake preset
      id: cmake_preset
      shell: bash
      run: |
        build_type_lower="${{ inputs.build-type }}"
        build_type_lower="${build_type_lower,,}"
        preset="rv${{ inputs.xlen }}-${{ inputs.toolchain }}-${build_type_lower}"
        echo "name=${preset}" >> "$GITHUB_OUTPUT"

    - name: Build Examples
      id: build-examples
      shell: bash
      run: |
        # export PATH=${{ inputs.llvm-dir }}/bin/:$PATH
        set -o pipefail
        cd ${{ inputs.examples-dir }}
        if [[ "${{ inputs.toolchain }}" == "llvm" ]]
        then
            cmake -S . -B build --preset ${{ steps.cmake_preset.outputs.name }} -DCMAKE_INSTALL_PREFIX=$(pwd)/build/install -DRISCV_ARCH=${{ inputs.arch }} -DRISCV_ABI=${{ inputs.abi }} -DRISCV_TOOLCHAIN_PREFIX=${{ inputs.gnu-dir }} -DRISCV_TOOLCHAIN_BASENAME=${{ inputs.gnu-name }} -DLLVM_DIR=${{ inputs.llvm_dir }} 2>&1 | tee -a etiss_sw_build_out.txt
        else
            cmake -S . -B build --preset ${{ steps.cmake_preset.outputs.name }} -DCMAKE_INSTALL_PREFIX=$(pwd)/build/install -DRISCV_ARCH=${{ inputs.arch }} -DRISCV_ABI=${{ inputs.abi }} -DRISCV_TOOLCHAIN_PREFIX=${{ inputs.gnu-dir }} -DRISCV_TOOLCHAIN_BASENAME=${{ inputs.gnu-name }} 2>&1 | tee -a etiss_sw_build_out.txt
        fi
        for prog in $(echo ${{ inputs.PROGS }} | sed 's/,/ /g'); do
            echo "prog=$prog" 2>&1 | tee -a etiss_sw_build_out.txt
            cmake --build build -j$(nproc) -t $prog 2>&1 | tee -a etiss_sw_build_out.txt
        done
        cmake --install build 2>&1 | tee -a etiss_sw_build_out.txt
        set +o pipefail
    - name: Add ETISS SW Build Summary (Failure)
      if: ${{ steps.build-examples.outcome == 'failure' }}
      shell: bash
      run: |
        echo "### ETISS SW Build Status" >> $GITHUB_STEP_SUMMARY
        echo "FAILING :x:" >> $GITHUB_STEP_SUMMARY
        echo >> $GITHUB_STEP_SUMMARY
        echo "**ETISS SW Build Outputs:**" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        cat etiss_riscv_examples/etiss_sw_build_out.txt >> $GITHUB_STEP_SUMMARY
        echo >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        # echo >> $GITHUB_STEP_SUMMARY
        exit 1
